version: '3.8'

services:
  mail-server:
    build: .
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    restart: always
    volumes:
      - fullchain.pem:${FULL_CHAIN}
      - privkey.pem:${PRIV_KEY}
volumes:
  fullchain.pem:
  privkey.pem: